options:
  install_sources:
    description: |
      list of extra apt sources, per charm-helpers standard
      format (a yaml list of strings encoded as a string). each source
      may be either a line that can be added directly to
      sources.list(5), or in the form ppa:<user>/<ppa-name> for adding
      personal package archives, or a distribution component to enable.
    type: string
    default: |
      - 'deb https://artifacts.elastic.co/packages/5.x/apt stable main'
  install_keys:
    description: |
      list of signing keys for install_sources package sources, per
      charmhelpers standard format (a yaml list of strings encoded as
      a string). the keys should be the full ascii armoured gpg public
      keys. while gpg key ids are also supported and looked up on a
      keyserver, operators should be aware that this mechanism is
      insecure. null can be used if a standard package signing key is
      used that will already be installed on the machine, and for ppa
      sources where the package signing key is securely retrieved from
      launchpad.
    type: string
    default: D88E42B4
  firewall_enabled:
    description: |
      this option will enable or disable the ufw. By default this is set to
      'false' since the firewall is never enabled when a machine or container
      is created with juju. Set to 'true' to enable firewall. Once enabled
      rules will be added when another charm has a relation with elasticsearch.
      This charm will be able to access elasticsearch on port 9200, while
      all the other traffice to that port will be blocked. Enabling the firewall
      will also allow port 22 from anywhere.
    type: boolean
    default: false
  cluster_name:
    description: |
      This sets the elasticsearch cluster name. This name is then added to the
      elasticsearch.yml file
    type: string
    default: "elasticsearch"
